### ISSUE TITLE
Unable to decode URL

### ISSUE THREAD

**Issue by sereivoanyong** [omochi/FineJSON#1]
Decoder throws an error saying type mismatch: type=JSONObject, expected object but string.

**Comment by omochi** [comment]
Could you share input JSON text and Swift code?

**Comment by sereivoanyong** [comment]
Actually it's quite simple.

`
{
  "url": "https://media.sproutsocial.com/uploads/2017/02/10x-featured-social-media-image-size.png"
}

struct A {
  let url: URL
}
`

**Comment by sereivoanyong** [comment]
Actually it's quite simple.

```
{
  "url": "https://media.sproutsocial.com/uploads/2017/02/10x-featured-social-media-image-size.png"
}

struct A {
  let url: URL
}
```

**Comment by omochi** [comment]
My encoder/decoder uses type's native `Codable` implementation.
So `URL`s coding is not `String`. It is object in JSON.

See below. 
It is intended behavior in this library.
https://github.com/omochi/FineJSON/blob/master/Tests/FineJSONTests/SimpleCodingTests.swift#L10

In `Foundation.JSONEncoder`, `.JSONDecoder`, 
coders has own logic to serialize `URL`, also `Date`.
I dislike this architecture.
Because it fragments serialization among coder families and keep it as same requires many efforts.

I recommend you not to use `URL` directly in serialization surface.

**Comment by sereivoanyong** [comment]
Oh, I see. This kind of behavior is not included in README, and for sure will cause confusion as well as frustration.

I end up adding a property wrapper.

```
@propertyWrapper
struct URLStringCoded: Codable {
  
  var wrappedValue: URL?
  
  init(from decoder: Decoder) throws {
    wrappedValue = try? URL(string: decoder.singleValueContainer().decode(String.self))
  }
  
  func encode(to encoder: Encoder) throws {
    try wrappedValue?.absoluteString.encode(to: encoder)
  }
}

struct A: Decodable {
  
  @URLStringCoded var url: URL?
}
```

**Comment by omochi** [comment]
I like solution with property wrapper too.
I am trying to use them recently.

Thanks to report.
I updated README.

https://github.com/omochi/FineJSON/blob/master/README.md#coding-for-url-date
